algoritmo "semnome"
// Função :
// Autor :
// Data : 21/05/2022
// Seção de Declarações
var
i, aleatorioMax, aleatorioMin, incremento: inteiro
inicio
repita
   aleatorio 1, 100
   leia(aleatorioMax)
   leia(aleatorioMin)
   aleatorio off
ate aleatorioMax >= aleatorioMin
limpatela
aleatorio 1,5
leia(incremento)
aleatorio off
limpatela

para i de aleatorioMin ate aleatorioMax passo incremento faca
escreval(i)

fimpara
fimalgoritmo
