algoritmo "Trabalhando com Tipos"
// Função :
// Autor :
// Data : 17/05/2022
// Seção de Declarações 
var
   palavra1, palavra2, palavra3: literal
   numero1, numero2, numero3: inteiro
inicio
      Escreval("Digite a primeira palavra: ")
      leia(palavra1)
      Escreval("Digite a segunda palavra: ")
      leia(palavra2)
      Escreval("Digite o primeiro numero: ")
      leia(numero1)
      Escreval("Digite segundo numero: ")
      leia(numero2)
      palavra3 <- palavra1 + " " + palavra2
      numero3 <- numero1 + numero2
      Escreval(palavra3)
      Escreval(numero3)
      
fimalgoritmo
